### ISSUE TITLE
Method `recommendItems()` fails to filter on `requestedTypeCodename`  when more complex custom filter query is provided

### ISSUE THREAD

**Issue by Suzii** [Kentico/kontent-recommendations-sdk-js#2]
### Brief bug description

Method `recommendItems()` fails to filter on `requestedTypeCodename`  when more complex custom filter query is provided

### Repro steps

1. Create a more complex filter query with `or`s
2. Specify `requestedTypeCodename`
3. Response also contains codenames of types other than requested type

### Expected behavior

The response is filtered by the `requestedTypeCodename` provided in the config.

### Additional context

Maybe you are not enclosing user-provided filter in parenthesis and then your custom `and type=XY` is added?

**Comment by strizr** [comment]
Missing outer parenthesis were the issue. I updated the API so that the user's filter is enclosed by default, should work now.

**Comment by Enngage** [comment]
Is there anything left to do in this repo, or can we close this?

**Comment by Suzii** [comment]
No, all good now, thanks :)

**Comment by strizr** [comment]
It is working now, confirmed!
