### ISSUE TITLE
The `recommendItems()` fails when trying to include `type` in the user-defined filter query

### ISSUE THREAD

**Issue by Suzii** [Kentico/kontent-recommendations-sdk-js#3]
### Brief bug description

The `recommendItems()` fails when trying to include `type` in the user-defined filter query

### Repro steps

1. Provide requestedTypeCodename=event
2. Provide a more complex custom filter including type, to workaround [another issue](https://github.com/Kentico/kontent-recommendations-sdk-js/issues/2): `(type=event) and (("domain_or_industry=accounting___finance" in 'properties') or ("domain_or_industry=entrepreneurship" in 'properties'))`
3. Call fails with ugly and unhelpful stacktrace

### Expected behavior

Either accepting the filter and return results, or at least some suggestion in the logged error about what I am doing wrong.

### Screenshots

![image](https://user-images.githubusercontent.com/8047248/96279784-70d00b80-0fd7-11eb-9d61-1e2059b9cd9f.png)

**Comment by Suzii** [comment]
I did not have the developer mode on, so maybe the stack trace would have been more helpful if I did. I can reproduce on Monday, id necessary.

**Comment by strizr** [comment]
The correct syntax would be ('type' == "event"), that is why the call is not going through.
